### ISSUE TITLE
Number of images is not consistent

### ISSUE THREAD

**Issue by MarcSzafraniec** [Mr-TalhaIlyas/CWD30#1]
Hello,

In the CWD30 paper, it is said that the dataset contains 219,778 images.
However, upon inspecting the data, downloaded via the link in the readme, I found a smaller number of 196,275 images.

Can you explain the reason why, and upload the corrected dataset if there's an error ? It would be useful to start using this dataset :)

Here is the breakdown by classes of the data that I have.

asian-flatsedge 12783
asiatic-dayflower 6018
bean 6260
bloodscale-sedge 6285
cockspur-grass 9296
cooper-leaf 4948
corn 6130
early-barnyard-grass 210
fall-panicum 9330
finger-grass 9207
foxtail-millet 5841
goosefoot 6110
great-millet 6765
green-foxtail 7594
green-gram 5447
henbit 7540
indian-goosegrass 9933
korean-dock 6018
livid-pigweed 7540
nipponicus-sedge 5445
peanut 6966
perilla 5016
poa-annua 210
proso-millet 6249
purslane 5655
red-bean 6459
redroot-pigweed 7540
sesame 5078
smooth-pigweed 7540
white-goosefoot 6862

**Comment by Mr-TalhaIlyas** [comment]
Hi,
Thanks for your interest.
Kindly refer to the Figure 2 in paper the MCW(mixed crops and weeds) section of data is not made public yet it consists of 23,502 images. So if you add both numbers you'll see the number of images match as mentioned. After it's labels are verified by farmers It'll be made public, along with dense pixel labels.
Moreover by the end of this year we'll update the existing models and add more models for classification, semantic and instance segmentation along with codes and weights as baselines. Which can be used. 
Thanks.

**Comment by MarcSzafraniec** [comment]
> Hi, Thanks for your interest. Kindly refer to the Figure 2 in paper the MCW(mixed crops and weeds) section of data is not made public yet it consists of 23,502 images. So if you add both numbers you'll see the number of images match as mentioned. After it's labels are verified by farmers It'll be made public, along with dense pixel labels. Moreover by the end of this year we'll update the existing models and add more models for classification, semantic and instance segmentation along with codes and weights as baselines. Which can be used. Thanks.

Thanks for your answer, it's clear for me now !
